# acl.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Access Control Lists
#
# Auto-generated by install script
# Date: Mon, 04 Jul 2022 12:15:44 +0000
*	@ALL	8
*	@user	8
territorial_community:*	@ALL	8
wiki:enregistrement	@user	2
wiki:reponse_territorial_community	@ALL	1
