<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: csdcunitwin
 * Date: Tue, 05 Jul 2022 09:21:24 +0000
 */

$conf['title'] = 'Complex Systems Digital Campus';
$conf['license'] = 'cc-by-sa';
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['htmlok'] = 1;
$conf['phpok'] = 1;
$conf['mailfrom'] = 'armandguelina@gmail.com';
$conf['userewrite'] = '2';
$conf['fnencode'] = 'utf-8';
$conf['autoplural'] = 1;
$conf['send404'] = 1;
$conf['plugin']['authldap']['attributes'] = array();
$conf['plugin']['infomail']['allowanonymous'] = 1;
$conf['plugin']['infomail']['archive'] = 1;
$conf['plugin']['infomail']['logmails'] = 1;
$conf['plugin']['smtp']['smtp_host'] = 'mail.privateemail.com';
$conf['plugin']['smtp']['smtp_port'] = 587;
$conf['plugin']['smtp']['smtp_ssl'] = 'tls';
$conf['plugin']['smtp']['auth_user'] = 'individual.members@cs-dc.info';
$conf['plugin']['smtp']['auth_pass'] = 'paul0000';
$conf['plugin']['smtp']['debug'] = 1;
