# users.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Userfile
#
# Auto-generated by install script
# Date: Mon, 04 Jul 2022 12:15:44 +0000
#
# Format:
# login:passwordhash:Real Name:email:groups,comma,separated

csdcunitwin:$2y$10$aUhHmy0oHTEu6DwYc5VEYOZV1kYKD4rtzhMJGvx5nm8G/dCxXuxi.:Complex Systems Digital Campus:paul.bourgine@polytechnique.edu:admin,user
