<?php
/*
 * Dokuwiki Preload File
 * Auto-generated by Site Export plugin 
 * Date: 2022-07-04 13:08:36
 */
/* SITE EXPORT *********************************************************** */
    if ( file_exists(DOKU_INC . 'lib/plugins/siteexport/preload.php') ) {
        include_once(DOKU_INC . 'lib/plugins/siteexport/preload.php');
        $siteexport_preload = new preload_plugin_siteexport();
        $siteexport_preload->__register_template();
        $siteexport_preload->__temporary_disable_plugins();
        unset($siteexport_preload);
    }
/* SITE EXPORT END *********************************************************** */
// end auto-generated content

